/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.Customer_DTO;
import DTO.DBConnection;
import DTO.Employee_DTO;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author vnngu
 */
public class CustomerGUI extends javax.swing.JFrame {

    /**
     * Creates new form CustomerGUI
     */
    Management management;
    public CustomerGUI() {
        initComponents();
        LoadDataCustomer();
    }
    public CustomerGUI(Management management) {
        initComponents();
        LoadDataCustomer();
        this.management = management;
    }
    private DefaultTableModel tableModel;
    private TableRowSorter<TableModel> rowSorter = null;
    Customer_DTO cus = new Customer_DTO();
    public void LoadDataCustomer(){
        tblStaff.removeAll();
        tableModel = new DefaultTableModel();
        tblStaff.getTableHeader().setFont(new Font("Tahoma",Font.BOLD,18));
        tblStaff.getTableHeader().setOpaque(false);
        tblStaff.getTableHeader().setBackground(Color.red);
        tblStaff.getTableHeader().setForeground(new Color(255,255,255));
        String columnName[] = {"Customer ID","Customer Name","Member Type","Point"};
        tableModel.setColumnIdentifiers(columnName);
        tblStaff.setModel(tableModel);
        rowSorter = new TableRowSorter<>(tblStaff.getModel());
        tblStaff.setRowSorter(rowSorter);

        txttim.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = txttim.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = txttim.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
        DBConnection con = new DBConnection();
        String sql = "Select * from Customer order by idcus asc";
         ResultSet rs = con.getData(sql);
        
        try {
            while(rs.next()) {
                String value[] = new String[4];
                value[0] = ""+rs.getInt(1);
                value[1] = rs.getString(2);
                if(rs.getInt(3) == 1)
                value[2] ="Vip";
                else
                    value[2]="Normal";
                value[3] = ""+rs.getInt(4);
                tableModel.addRow(value);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ShowTime.class.getName()).log(Level.SEVERE, null, ex);
        }
        con.CloseConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        lblDelete = new javax.swing.JLabel();
        lblInsert = new javax.swing.JLabel();
        lblEdit = new javax.swing.JLabel();
        txttim = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(13, 23, 45));
        jLabel21.setText("Customer");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 240, -1));

        jLabel13.setBackground(new java.awt.Color(255, 153, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/CG4.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 440, 200));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/icons8-jdownloader-96.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 110, 200));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/icons8-back-arrow-64.png"))); // NOI18N
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, 90, 90));

        tblStaff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblStaff.setFocusable(false);
        tblStaff.setGridColor(new java.awt.Color(51, 51, 51));
        tblStaff.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblStaff.setRowHeight(25);
        tblStaff.setSelectionBackground(new java.awt.Color(224, 78, 72));
        tblStaff.setShowGrid(false);
        tblStaff.setShowHorizontalLines(true);
        tblStaff.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblStaff);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 970, 390));

        lblDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/rubber (1)90x90.png"))); // NOI18N
        lblDelete.setText("jLabel2");
        lblDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeleteMouseClicked(evt);
            }
        });
        jPanel5.add(lblDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 90, 90));

        lblInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/mathematics90x90.png"))); // NOI18N
        lblInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInsertMouseClicked(evt);
            }
        });
        jPanel5.add(lblInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 90, 90));

        lblEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/registe90x90.png"))); // NOI18N
        lblEdit.setText("jLabel2");
        lblEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditMouseClicked(evt);
            }
        });
        jPanel5.add(lblEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 90, 90));
        jPanel5.add(txttim, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 570, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/Lovepik_com-611710438-Children cartoon hand drawn magnifying glass icon (1).png"))); // NOI18N
        jLabel5.setText("Tìm");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 80, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1030, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        management.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lblDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteMouseClicked

        int index = tblStaff.getSelectedRow();
        int idShowtime =Integer.parseInt(tableModel.getValueAt(index,0).toString());
        cus.setId(idShowtime);
        if(cus.deleteCus())
        new Success("Delete Success!");
        else
        new ErrorGUI("Delete Fail!");
        LoadDataCustomer();
    }//GEN-LAST:event_lblDeleteMouseClicked

    private void lblInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsertMouseClicked
        new FormCustomer(this).setVisible(true);
    }//GEN-LAST:event_lblInsertMouseClicked

    private void lblEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseClicked
        // TODO add your handling code here:
        int index = tblStaff.getSelectedRow();
        int idemp = Integer.parseInt(tableModel.getValueAt(index,0).toString());
        String name = tableModel.getValueAt(index,1).toString();
        int member = 0;
        if(tableModel.getValueAt(index,2).toString().compareTo("Vip") == 0)
            member = 1;
        int point = Integer.parseInt(tableModel.getValueAt(index,3).toString());
        //System.out.println(mvAge);
        cus = new Customer_DTO(idemp, name, member,point);
        if(cus.updateCus()){
            new Success("Update Success!");
            LoadDataCustomer();
        }else
        new ErrorGUI("Update Fail!");

    }//GEN-LAST:event_lblEditMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblInsert;
    private javax.swing.JTable tblStaff;
    private javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables
}
