/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.DBConnection;
import DTO.Employee_DTO;
import DTO.ShowTime_DTO;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Nhut
 */
public class HumanRescource extends javax.swing.JFrame {

    /**
     * Creates new form HumanRescource
     */
    private DefaultTableModel tableModel;
    private TableRowSorter<TableModel> rowSorter = null;
    Employee_DTO emp = new Employee_DTO();
    public HumanRescource() {
        initComponents();
        LoadDataStaff();
    }
    Management management;
    public HumanRescource(Management management) {
        initComponents();
        LoadDataStaff();
        this.management = management;
    }
    
    public void LoadDataStaff(){
        tableModel = new DefaultTableModel();
        tblStaff.getTableHeader().setFont(new Font("Tahoma",Font.BOLD,18));
        tblStaff.getTableHeader().setOpaque(false);
        tblStaff.getTableHeader().setBackground(Color.red);
        tblStaff.getTableHeader().setForeground(new Color(255,255,255));
        String columnName[] = {"Staff ID","Name","Date of birth","User","Pass","Role"};
        tableModel.setColumnIdentifiers(columnName);
        tblStaff.setModel(tableModel);
        rowSorter = new TableRowSorter<>(tblStaff.getModel());
        tblStaff.setRowSorter(rowSorter);

        txttim.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = txttim.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = txttim.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
        DBConnection con = new DBConnection();
        String sql = "Select * from Staff where role = 'Staff' order by id_staff";
        if(LOGIN1.emp_login.getEmp_role().equalsIgnoreCase("Admin"))
            sql = "Select * from Staff where role = 'Staff' or role = 'Manager' order by id_staff";

         ResultSet rs = con.getData(sql);
        
        try {
            while(rs.next()) {
                String value[] = new String[6];
                value[0] = rs.getString("ID_STAFF");
                value[1] = rs.getString("NAME_STAFF");
                value[2] = rs.getDate("DATE_bIRTH").toString();
                //Time timestart = new Time(rs.getTimestamp("TIME_START").getTime());
                //value[3] = timestart.toString().substring(0, 5);
                //Time timeend = new Time(rs.getTimestamp("TIME_END").getTime());
                //value[4] = timeend.toString().substring(0, 5);
                value[3] = rs.getString("USERNAME");
                value[4] = rs.getString("PASSWORD");
                value[5] = rs.getString("Role");
                tableModel.addRow(value);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ShowTime.class.getName()).log(Level.SEVERE, null, ex);
        }
        con.CloseConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        lblDelete = new javax.swing.JLabel();
        lblInsert = new javax.swing.JLabel();
        lblEdit = new javax.swing.JLabel();
        txttim = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(13, 23, 45));
        jLabel21.setText("Staff");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 180, -1));

        jLabel13.setBackground(new java.awt.Color(255, 153, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/CG4.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 440, 200));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/icons8-jdownloader-96.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 110, 200));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/icons8-back-arrow-64.png"))); // NOI18N
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, 90, 90));

        tblStaff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblStaff.setFocusable(false);
        tblStaff.setGridColor(new java.awt.Color(51, 51, 51));
        tblStaff.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblStaff.setRowHeight(25);
        tblStaff.setSelectionBackground(new java.awt.Color(224, 78, 72));
        tblStaff.setShowGrid(false);
        tblStaff.setShowHorizontalLines(true);
        tblStaff.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblStaff);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 970, 390));

        lblDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/rubber (1)90x90.png"))); // NOI18N
        lblDelete.setText("jLabel2");
        lblDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeleteMouseClicked(evt);
            }
        });
        jPanel5.add(lblDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 90, 90));

        lblInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/mathematics90x90.png"))); // NOI18N
        lblInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInsertMouseClicked(evt);
            }
        });
        jPanel5.add(lblInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 90, 90));

        lblEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/registe90x90.png"))); // NOI18N
        lblEdit.setText("jLabel2");
        lblEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditMouseClicked(evt);
            }
        });
        jPanel5.add(lblEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 90, 90));
        jPanel5.add(txttim, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 290, 40));

        jLabel5.setText("Tìm");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 30, 40));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1020, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        management.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lblDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteMouseClicked

        int index = tblStaff.getSelectedRow();
        int idShowtime =Integer.parseInt(tableModel.getValueAt(index,0).toString());
        emp.setEmp_id(idShowtime);
        if(emp.deleteStaff())
            new Success("Delete Success!");
        else
            new ErrorGUI("Delete Fail!");
        LoadDataStaff();
    }//GEN-LAST:event_lblDeleteMouseClicked

    private void lblInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsertMouseClicked
        new FormInsertEmployee(this).setVisible(true);
    }//GEN-LAST:event_lblInsertMouseClicked

    private void lblEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseClicked
        // TODO add your handling code here:
        int index = tblStaff.getSelectedRow();
        int idemp = Integer.parseInt(tableModel.getValueAt(index,0).toString());
        String name = tableModel.getValueAt(index,1).toString();
        Date date = Date.valueOf(tableModel.getValueAt(index,2).toString());
        String user = tableModel.getValueAt(index,3).toString();
        String pass = tableModel.getValueAt(index,4).toString();
        String role = tableModel.getValueAt(index,5).toString();
        //System.out.println(mvAge);
       emp = new Employee_DTO(idemp, name, date, user, pass,role);
       if(emp.updateStaff()){
           new Success("Update Success!");
           LoadDataStaff();
       }else
           new ErrorGUI("Update Fail!");
       
    }//GEN-LAST:event_lblEditMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HumanRescource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HumanRescource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HumanRescource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HumanRescource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HumanRescource().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblInsert;
    private javax.swing.JTable tblStaff;
    private javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables
}
