/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.Movie_DTO;
import java.awt.Color;
import java.awt.Font;
import java.util.Vector;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Nhut
 */
public class Movie extends javax.swing.JFrame {

    /**
     * Creates new form Movie
     */
    private DefaultTableModel tableModel;
    Movie_DTO movie_DTO = new Movie_DTO();
    
    public Movie() {
        initComponents();
        LoadDataMovie();
        
    }
    public Management management;
    public Movie(Management management) {
        initComponents();
        LoadDataMovie();
        this.management = management;
        
    }
    private TableRowSorter<TableModel> rowSorter = null;
    

    
    public void LoadDataMovie(){
        Management.listMovie.clear();
        Management.listMovie = new Movie_DTO().Display("Select * from movie order by id asc");
        tableModel = new DefaultTableModel();
        tblMovie.getTableHeader().setFont(new Font("Tahoma",Font.BOLD,18));
        tblMovie.getTableHeader().setOpaque(false);
        tblMovie.getTableHeader().setBackground(Color.red);
        tblMovie.getTableHeader().setForeground(new Color(255,255,255));
        String columnName[] = {"Mã Phim","Tên Phim","Thể loại","Độ Tuổi","Thời lượng"};
        tableModel.setColumnIdentifiers(columnName);
        tblMovie.setModel(tableModel);
        rowSorter = new TableRowSorter<>(tblMovie.getModel());
        tblMovie.setRowSorter(rowSorter);

        txttim.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = txttim.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = txttim.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
        Vector<Movie_DTO> vcmv = movie_DTO.Display("Select * from movie order by id asc");
        for (Movie_DTO i : vcmv) {
            String value[] = new String[5];
            value[0] = ""+i.getID();
            value[1] = i.getMovie_name();
            value[2] = i.getMovie_type();
            value[3] = i.getMovie_age();
            value[4] = ""+i.getDuration_min();
            tableModel.addRow(value);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovie = new javax.swing.JTable();
        lblDelete = new javax.swing.JLabel();
        lblInsert = new javax.swing.JLabel();
        lblEdit = new javax.swing.JLabel();
        txttim = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(13, 23, 45));
        jLabel21.setText("Movie");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, -1, -1));
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 49, -1, -1));

        jLabel13.setBackground(new java.awt.Color(36, 47, 65));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/CG4.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 450, 200));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/icons8-jdownloader-96.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 110, 200));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 1040, 200));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/icons8-back-arrow-64.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 500, 90, 90));

        tblMovie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblMovie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblMovie.setFocusable(false);
        tblMovie.setGridColor(new java.awt.Color(51, 51, 51));
        tblMovie.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblMovie.setRowHeight(25);
        tblMovie.setSelectionBackground(new java.awt.Color(224, 78, 72));
        tblMovie.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblMovie.setShowGrid(false);
        tblMovie.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblMovie);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 990, 350));

        lblDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/rubber (1)90x90.png"))); // NOI18N
        lblDelete.setText("jLabel2");
        lblDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeleteMouseClicked(evt);
            }
        });
        jPanel3.add(lblDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 90, 90));

        lblInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/mathematics90x90.png"))); // NOI18N
        lblInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInsertMouseClicked(evt);
            }
        });
        jPanel3.add(lblInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 90, 90));

        lblEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/registe90x90.png"))); // NOI18N
        lblEdit.setText("jLabel2");
        lblEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditMouseClicked(evt);
            }
        });
        jPanel3.add(lblEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 90, 90));
        jPanel3.add(txttim, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 290, 40));

        jLabel5.setText("Tìm");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 30, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 200, 1040, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteMouseClicked
        // TODO add your handling code here:
        int index = tblMovie.getSelectedRow();
        int IDMovie =Integer.parseInt(tableModel.getValueAt(index,0).toString());
        movie_DTO.deleteMovie(IDMovie);
        LoadDataMovie();
    }//GEN-LAST:event_lblDeleteMouseClicked

    private void lblInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsertMouseClicked
        // TODO add your handling code here:
        new FormInsertMovie(this).setVisible(true);

    }//GEN-LAST:event_lblInsertMouseClicked

    private void lblEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseClicked
        // TODO add your handling code here:
        
        int index = tblMovie.getSelectedRow();
        int idMovie =Integer.parseInt(tableModel.getValueAt(index,0).toString());
        String mvName = tableModel.getValueAt(index,1).toString();
        System.out.println(mvName);
        String mvType = tableModel.getValueAt(index,2).toString();
        int duration = Integer.parseInt(tableModel.getValueAt(index,4).toString());
        String mvAge = "" + tableModel.getValueAt(index,3);
            //System.out.println(mvAge);
            movie_DTO.updateMovie(idMovie,mvName,mvType,duration,mvAge.toString());
        LoadDataMovie();
    }//GEN-LAST:event_lblEditMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        management.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void  run() {
                new Movie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblInsert;
    private javax.swing.JTable tblMovie;
    private javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables
}
