/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.Bill;
import DTO.ShowTime_DTO;
import javax.swing.JLabel;

/**
 *
 * @author vnngu
 */
public class PaymentDemo extends javax.swing.JFrame {

    /**
     * Creates new form PaymentDemo
     */
    public PaymentDemo() {
        initComponents();
    }
   // JLabel lbPrice;
    Bill bill = new Bill();
    public PaymentDemo(String lbPrice , Bill bill) {
        initComponents();
        this.txtMoney.setText(lbPrice);
        this.bill = bill;
        txtMoney.setText(lbPrice);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMoney = new javax.swing.JTextField();
        btnPay = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn500k = new javax.swing.JButton();
        btn200k = new javax.swing.JButton();
        btn100k = new javax.swing.JButton();
        btn50k = new javax.swing.JButton();
        btn20k = new javax.swing.JButton();
        btn10k = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMoney.setText("jTextField1");
        getContentPane().add(txtMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 300, 50));

        btnPay.setText("Thanh toán");
        getContentPane().add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, 70));

        jButton2.setText("Huỷ");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 90, 70));

        btn500k.setText("500k");
        getContentPane().add(btn500k, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        btn200k.setText("200k");
        getContentPane().add(btn200k, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        btn100k.setText("100k");
        getContentPane().add(btn100k, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        btn50k.setText("50k");
        getContentPane().add(btn50k, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        btn20k.setText("20k");
        getContentPane().add(btn20k, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        btn10k.setText("10k");
        getContentPane().add(btn10k, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn100k;
    private javax.swing.JButton btn10k;
    private javax.swing.JButton btn200k;
    private javax.swing.JButton btn20k;
    private javax.swing.JButton btn500k;
    private javax.swing.JButton btn50k;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtMoney;
    // End of variables declaration//GEN-END:variables
}
