/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.Bill;
import DTO.Bill_Detail_DTO;
import DTO.DBConnection;
import DTO.Movie_DTO;
import DTO.Seat_Status;
import DTO.ShowTime_DTO;
import DTO.Ticket_DTO;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dell
 */
public class Payment extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    Bill bill = new Bill();
    Bill_Detail_DTO bill_detail = new Bill_Detail_DTO();
    DefaultTableModel tbModel = new DefaultTableModel();
    Vector<Bill_Detail_DTO> listBill_Detail_DTOs = new Vector<>();
    Vector<Seat_Status> listseatchoose = new Vector<>();
    GUIMovie guimv;
    /**
     * Creates new form NewJFrame
     */
    public Payment() {
        initComponents();
        
    }
//    public Payment(String cash, Bill bill,Vector<Seat_Status> listseatchoose,ShowTime_DTO stChoose, Movie_DTO mvChoose) {
//        initComponents();
//        this.bill = bill;
//        lblCash.setText(cash);
//        this.listseatchoose = listseatchoose;
//        String nameCl[] = {"Tên Phim","Phòng","Suất chiếu","Ghế","Giá"}; 
//        tbModel.setColumnIdentifiers(nameCl);
//           for (var item : listseatchoose) {
//               String value[] = new String[5];
//               value[0] = mvChoose.getMovie_name();
//               value[1] = "" + stChoose.getID_Room();
//               value[2] = stChoose.getTime_Start() + "-" + stChoose.getTime_End();
//               value[3] = item.getRowString() + "" + item.getNumber();
//               value[4] = "" + stChoose.getCost();
//               tbModel.addRow(value);
//           }
//           tbCash.setModel(tbModel);
//    }
    public Payment(String cash, Bill bill,Vector<Bill_Detail_DTO> listbilldetailDTOs,
            SEATS s,ShowTime_DTO stChoose,Movie_DTO mvChoose, Vector<Ticket_DTO> listticket, GUIMovie guimv) {
        initComponents();
        this.guimv = guimv;
        this.bill = bill;
        lblCash.setText(cash);
        this.listBill_Detail_DTOs = listbilldetailDTOs;
        this.listseatchoose = listseatchoose;
        String nameCl[] = {"Tên Phim","Phòng","Suất chiếu","Ghế","Loai ve","Giá"}; 
        tbModel.setColumnIdentifiers(nameCl);
            int i = 0;
           for (var item : s.getListSeatChooseAdult()) {
               String value[] = new String[6];
               value[0] = mvChoose.getMovie_name();
               value[1] = "" + stChoose.getID_Room();
               value[2] = stChoose.getTime_Start() + "-" + stChoose.getTime_End();
               value[3] = item.getRowString() + "" + item.getNumber();
               value[4] = listticket.get(0).getTicket_Type();
               value[5] = "" + listbilldetailDTOs.get(i).getPrice();
               i++;
               tbModel.addRow(value);
           }
            for (var item : s.getListSeatChooseChild()) {
               String value[] = new String[6];
               value[0] = mvChoose.getMovie_name();
               value[1] = "" + stChoose.getID_Room();
               value[2] = stChoose.getTime_Start() + "-" + stChoose.getTime_End();
               value[3] = item.getRowString() + "" + item.getNumber();
               value[4] = listticket.get(1).getTicket_Type();
               value[5] = "" + listbilldetailDTOs.get(i).getPrice();
               i++;
               tbModel.addRow(value);
           }
           tbCash.setModel(tbModel);
    }    
//    public void TinhTien(){
//        if(txtTienKhach.getText().compareTo("") == 0){
//            
//        }
//    }
//    confirm confirm = new confirm();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblCash = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCash = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblNameCus = new javax.swing.JLabel();
        lblVip = new javax.swing.JLabel();
        txtCus_ID = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblPoint = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setFocusable(false);
        setForeground(new java.awt.Color(255, 0, 51));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 720));
        setType(java.awt.Window.Type.POPUP);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(Color.BLACK);
        jPanel1.setOpaque(true);
        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(Color.white);
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Cash VND");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, 60));

        lblCash.setBackground(new java.awt.Color(51, 51, 51));
        lblCash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCash.setForeground(new java.awt.Color(255, 255, 255));
        lblCash.setOpaque(true);
        jPanel1.add(lblCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 330, 60));

        jButton1.setBackground(Color.GRAY);
        jButton1.setText("Xác nhận");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 117, 92));

        jButton2.setBackground(Color.GRAY);
        jButton2.setText("Huỷ");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 117, 92));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 890, 280));

        jPanel4.setBackground(Color.BLACK);
        jPanel4.setOpaque(true);
        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, 68));

        jLabel6.setForeground(Color.white);
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Thông tin order");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, -1));

        tbCash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbCash.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbCash.setFocusable(false);
        tbCash.setGridColor(new java.awt.Color(51, 51, 51));
        tbCash.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbCash.setRowHeight(25);
        tbCash.setSelectionBackground(new java.awt.Color(224, 78, 72));
        tbCash.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbCash.setShowGrid(false);
        tbCash.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbCash);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 440, 290));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 74, 480, 360));

        jPanel8.setBackground(Color.BLACK);
        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel8MouseDragged(evt);
            }
        });
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/icons8-back-arrow-64.png"))); // NOI18N
        jButton11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton11.setBorderPainted(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton11.setFocusable(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 805, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 80));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Tên khách hàng:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Thành viên: ");

        lblNameCus.setBackground(new java.awt.Color(255, 255, 255));
        lblNameCus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNameCus.setOpaque(true);

        lblVip.setBackground(new java.awt.Color(255, 255, 255));
        lblVip.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVip.setOpaque(true);

        txtCus_ID.setBackground(new java.awt.Color(204, 204, 204));
        txtCus_ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCus_ID.setText("Mã khách hàng");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/Lovepik_com-611710438-Children cartoon hand drawn magnifying glass icon (1).png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Point");

        lblPoint.setBackground(new java.awt.Color(255, 255, 255));
        lblPoint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPoint.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel17))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNameCus, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblVip, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtCus_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton7)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCus_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(lblNameCus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(lblVip, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 420, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           // TODO add your handling code here:
//                          confirm.setVisible(true);
        if(txtCus_ID.getText().compareTo("Mã khách hàng") != 0){
            bill.setCus_id(Integer.parseInt(txtCus_ID.getText()));
        }
        else
            bill.setCus_id(0);
        
            if(bill.insertBill(bill.getStaff_id(), bill.getCus_id(), bill.getDate(), bill.getPrice(),bill.getShowTime_id()))
            {
            try {
                DBConnection con = new DBConnection();
                ResultSet rs = con.getData("Select max(bill_id)as id from bill ");
                if(rs.next()){
                        int idbill = rs.getInt("id");
                        con.CloseConnection();
                    for (Bill_Detail_DTO item : listBill_Detail_DTOs) {
                        bill_detail.insertBill_Detail(idbill, item.getSeat_Status_ID(),item.getPrice(), item.getTicket_id());
                    }
                }
                new Success("Thanh toan thanh cong !");
            } catch (SQLException ex) {
                new ErrorGUI("Thanh toan that bai!");
                Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else{
                new ErrorGUI("Thanh toan that bai!");
            }
        
        new GUIMovie(guimv.getEmp(),guimv.opt);
        guimv.dispose();
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
//                 confirm.setVisible(true);

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
 
    }//GEN-LAST:event_formMouseDragged

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel8MouseDragged

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel8MousePressed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Connection con = new DBConnection().getConnectionManager();
        String sql = "Select * from Customer where IDcus = " + txtCus_ID.getText();
        System.out.println(sql);
        try {        
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                lblNameCus.setText(rs.getString("Name"));
                lblPoint.setText(""+rs.getInt("Point"));
                if(rs.getInt("Member") == 1){
                    lblVip.setText("Vip");
                }
                else if(rs.getInt("Member") == 0){
                    lblVip.setText("Normal");
                }
  
            }
        } catch (SQLException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCash;
    private javax.swing.JLabel lblNameCus;
    private javax.swing.JLabel lblPoint;
    private javax.swing.JLabel lblVip;
    private javax.swing.JTable tbCash;
    private javax.swing.JTextField txtCus_ID;
    // End of variables declaration//GEN-END:variables
}
