/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.Customer_DTO;
import DTO.DBConnection;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nhut
 */
public class Transaction extends javax.swing.JFrame {

    /**
     * Creates new form Transaction
     */
    private DefaultTableModel tableModel;
    public Transaction() {
        initComponents();
        LoadDataTransaction();
    }
    Management management;
    public Transaction(Management management) {
        initComponents();
        LoadDataTransaction();
        this.management = management;
    }
    public void LoadDataTransaction(){
        tableModel = new DefaultTableModel();
        tblTransaction.getTableHeader().setFont(new Font("Tahoma",Font.BOLD,18));
        tblTransaction.getTableHeader().setOpaque(false);
        tblTransaction.getTableHeader().setBackground(Color.red);
        tblTransaction.getTableHeader().setForeground(new Color(255,255,255));
        String columnName[] = {"Bill","Staff","Customer","Movie","Date","Time","Total"};
        tableModel.setColumnIdentifiers(columnName);
        tblTransaction.setModel(tableModel);
        
        DBConnection con = new DBConnection();
        ResultSet rscus = con.getData("Select * from Customer");
        Vector<Customer_DTO> listCus = new Vector<>();
        try {
            while(rscus.next()){
                listCus.add(new Customer_DTO(rscus.getInt("IDcus"), rscus.getString("Name"), rscus.getInt("Member"),rscus.getInt("Point")));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Transaction.class.getName()).log(Level.SEVERE, null, ex);
        }
        con.CloseConnection();
        String sql = "select b.*,mv.movie_name,sta.name_staff,st.time_start,st.time_end"
                + " from bill b,staff sta, movie mv, showtime st"
                + " where b.showtime_id = st.ID and"
                + " b.staff_id = sta.id_staff and"
                + " mv.id = st.movie_id order by b.bill_id";
        System.out.println(sql);
        
        DBConnection con2 = new DBConnection();
         ResultSet rsbill = con2.getData(sql);
        
        try {
            while(rsbill.next()) {
                String value[] = new String[7];
                value[0] = ""+rsbill.getInt("bill_ID");
                value[1] = rsbill.getString("name_staff");
                value[3] = rsbill.getString("Movie_Name");
                if(!listCus.isEmpty())
                {   for (Customer_DTO item : listCus) {
                        if(item.getId()==rsbill.getInt("cus_id"))
                        value[2] = item.getName();
                        break;
                    }
                    
                }else
                    value[2] = "null";
                value[4] = rsbill.getString("Date_bill");
                value[5] = rsbill.getString("time_start") + "-" + rsbill.getString("time_end");
                value[6] = ""+rsbill.getInt("price");
                tableModel.addRow(value);
            }
        } catch (SQLException ex) {

            Logger.getLogger(ShowTime.class.getName()).log(Level.SEVERE, null, ex);
        }
        con2.CloseConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaction = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(13, 23, 45));
        jLabel21.setText("Transaction");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 44, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 153, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/CG4.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 440, 200));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/icons8-jdownloader-96.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 110, 180));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 1050, 180));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image/icons8-back-arrow-64.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 500, 90, 90));

        tblTransaction.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblTransaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblTransaction.setFocusable(false);
        tblTransaction.setGridColor(new java.awt.Color(51, 51, 51));
        tblTransaction.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblTransaction.setName(""); // NOI18N
        tblTransaction.setRowHeight(25);
        tblTransaction.setSelectionBackground(new java.awt.Color(224, 78, 72));
        tblTransaction.setShowGrid(false);
        tblTransaction.setShowHorizontalLines(true);
        tblTransaction.getTableHeader().setReorderingAllowed(false);
        tblTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransactionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaction);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 850, 510));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 290, 40));

        jLabel5.setText("Tìm");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 30, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1040, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        management.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tblTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransactionMouseClicked
        // TODO add your handling code here:
        if(tblTransaction.getSelectedRow() != -1){
            int index = tblTransaction.getSelectedRow();
            new FormBill_Detail(Integer.parseInt(tblTransaction.getValueAt(index, 0).toString())).setVisible(true);
        }
    }//GEN-LAST:event_tblTransactionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblTransaction;
    // End of variables declaration//GEN-END:variables
}
