--------------------------------------------------------
--  File created - Friday-July-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BILL_DETAIL_FOOD
--------------------------------------------------------

  CREATE TABLE "C##USERSQL"."BILL_DETAIL_FOOD" 
   (	"BILL_DETAIL_FOOD" NUMBER(*,0) DEFAULT "C##USERSQL"."SQ"."NEXTVAL", 
	"BILL_ID" NUMBER(*,0), 
	"FOOD_ID" NUMBER(*,0), 
	"AMOUNT" NUMBER(*,0), 
	"PRICE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BILL
--------------------------------------------------------

  CREATE TABLE "C##USERSQL"."BILL" 
   (	"BILL_ID" NUMBER(*,0) DEFAULT "C##USERSQL"."AUTO_TANG_BILIDL"."NEXTVAL", 
	"STAFF_ID" NUMBER(*,0), 
	"CUS_ID" NUMBER(*,0), 
	"DATE_BILL" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER, 
	"SHOWTIME_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BILL_DETAIL_SEAT
--------------------------------------------------------

  CREATE TABLE "C##USERSQL"."BILL_DETAIL_SEAT" 
   (	"BILL_DETAIL_ID" NUMBER(*,0) DEFAULT "C##USERSQL"."AUTO_TANG_ID_BILL_DETAIL_SEAT"."NEXTVAL", 
	"BILL_ID" NUMBER(*,0), 
	"SEAT_STATUS_ID" NUMBER(*,0), 
	"PRICE" NUMBER, 
	"TICKET_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "C##USERSQL"."CUSTOMER" 
   (	"IDCUS" NUMBER(*,0), 
	"NAME" NVARCHAR2(20), 
	"MEMBER" NUMBER(*,0), 
	"POINT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FOOD
--------------------------------------------------------

  CREATE TABLE "C##USERSQL"."FOOD" 
   (	"FOOD_ID" NUMBER(*,0), 
	"FOOD_NAME" NVARCHAR2(20), 
	"PRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MOVIE
--------------------------------------------------------

  CREATE TABLE "C##USERSQL"."MOVIE" 
   (	"ID" NUMBER(*,0) DEFAULT NULL, 
	"MOVIE_NAME" NVARCHAR2(20), 
	"MOVIE_TYPE" NVARCHAR2(20), 
	"MOVIE_DURATION" NUMBER(*,0), 
	"MOVIE_AGE" NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROOM
--------------------------------------------------------

  CREATE TABLE "C##USERSQL"."ROOM" 
   (	"IDROOM" NUMBER(*,0), 
	"SEATS_NO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SEAT
--------------------------------------------------------

  CREATE TABLE "C##USERSQL"."SEAT" 
   (	"IDSEAT" NUMBER(*,0) DEFAULT "C##USERSQL"."AUTO_TANG_ID_SEAT"."NEXTVAL", 
	"ROW_SEAT" VARCHAR2(20 BYTE), 
	"NUMBER_SEAT" NUMBER(*,0), 
	"IDROOM" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SEAT_STATUS
--------------------------------------------------------

  CREATE TABLE "C##USERSQL"."SEAT_STATUS" 
   (	"IDSEAT_STATUS" NUMBER(*,0) DEFAULT NULL, 
	"ID_SHOWTIME" NUMBER(*,0), 
	"ID_SEAT" NUMBER(*,0), 
	"STATUS" NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SHOWTIME
--------------------------------------------------------

  CREATE TABLE "C##USERSQL"."SHOWTIME" 
   (	"ID" NUMBER(*,0), 
	"MOVIE_ID" NUMBER(*,0), 
	"ROOM_ID" NUMBER(*,0), 
	"TIME_START" VARCHAR2(20 BYTE), 
	"COST" NUMBER(*,0), 
	"TIME_END" VARCHAR2(20 BYTE), 
	"DATE_ST" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "C##USERSQL"."STAFF" 
   (	"ID_STAFF" NUMBER(*,0), 
	"NAME_STAFF" NVARCHAR2(20), 
	"DATE_BIRTH" DATE, 
	"USERNAME" NVARCHAR2(20), 
	"PASSWORD" NVARCHAR2(20), 
	"ROLE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TICKET
--------------------------------------------------------

  CREATE TABLE "C##USERSQL"."TICKET" 
   (	"TICKET_ID" NUMBER(*,0) DEFAULT NULL, 
	"SHOWTIME_ID" NUMBER(*,0), 
	"TICKET_TYPE" NVARCHAR2(20), 
	"PRICE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##USERSQL.BILL_DETAIL_FOOD
SET DEFINE OFF;
REM INSERTING into C##USERSQL.BILL
SET DEFINE OFF;
Insert into C##USERSQL.BILL (BILL_ID,STAFF_ID,CUS_ID,DATE_BILL,PRICE,SHOWTIME_ID) values (22,4,1,'01-JUL-20',240000,5);
Insert into C##USERSQL.BILL (BILL_ID,STAFF_ID,CUS_ID,DATE_BILL,PRICE,SHOWTIME_ID) values (61,185121361,1,'09-JUL-20',360000,11);
Insert into C##USERSQL.BILL (BILL_ID,STAFF_ID,CUS_ID,DATE_BILL,PRICE,SHOWTIME_ID) values (26,4,2,'09-JUL-20',200000,11);
Insert into C##USERSQL.BILL (BILL_ID,STAFF_ID,CUS_ID,DATE_BILL,PRICE,SHOWTIME_ID) values (42,4,1,'09-JUL-20',380000,11);
Insert into C##USERSQL.BILL (BILL_ID,STAFF_ID,CUS_ID,DATE_BILL,PRICE,SHOWTIME_ID) values (24,4,1,'09-JUL-20',200000,11);
Insert into C##USERSQL.BILL (BILL_ID,STAFF_ID,CUS_ID,DATE_BILL,PRICE,SHOWTIME_ID) values (27,4,1,'09-JUL-20',200000,11);
Insert into C##USERSQL.BILL (BILL_ID,STAFF_ID,CUS_ID,DATE_BILL,PRICE,SHOWTIME_ID) values (45,4,1,'09-JUL-20',160000,13);
Insert into C##USERSQL.BILL (BILL_ID,STAFF_ID,CUS_ID,DATE_BILL,PRICE,SHOWTIME_ID) values (46,4,3,'09-JUL-20',300000,12);
Insert into C##USERSQL.BILL (BILL_ID,STAFF_ID,CUS_ID,DATE_BILL,PRICE,SHOWTIME_ID) values (41,4,1,'09-JUL-20',288000,13);
Insert into C##USERSQL.BILL (BILL_ID,STAFF_ID,CUS_ID,DATE_BILL,PRICE,SHOWTIME_ID) values (43,4,1,'09-JUL-20',380000,11);
Insert into C##USERSQL.BILL (BILL_ID,STAFF_ID,CUS_ID,DATE_BILL,PRICE,SHOWTIME_ID) values (21,4,null,'01-JUL-20',140000,5);
Insert into C##USERSQL.BILL (BILL_ID,STAFF_ID,CUS_ID,DATE_BILL,PRICE,SHOWTIME_ID) values (44,4,1,'09-JUL-20',360000,11);
Insert into C##USERSQL.BILL (BILL_ID,STAFF_ID,CUS_ID,DATE_BILL,PRICE,SHOWTIME_ID) values (29,4,2,'09-JUL-20',200000,11);
REM INSERTING into C##USERSQL.BILL_DETAIL_SEAT
SET DEFINE OFF;
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (42,41,464,80000,363);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (20,21,113,70000,5);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (33,29,318,100000,309);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (47,44,321,100000,309);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (55,46,435,100000,361);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (61,61,325,100000,309);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (21,21,114,70000,5);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (43,41,465,64000,364);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (22,22,117,70000,5);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (48,44,322,100000,309);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (62,61,326,100000,309);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (30,27,315,100000,309);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (23,22,118,70000,5);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (28,26,313,100000,309);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (44,41,466,64000,364);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (45,42,319,100000,309);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (46,42,320,100000,309);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (49,44,323,80000,310);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (63,61,327,80000,310);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (24,22,121,50000,6);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (26,24,311,100000,309);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (29,26,314,100000,309);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (31,27,316,100000,309);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (50,44,324,80000,310);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (51,45,467,80000,363);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (53,46,433,100000,361);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (64,61,328,80000,310);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (32,29,317,100000,309);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (41,41,463,80000,363);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (25,22,122,50000,6);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (27,24,312,100000,309);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (52,45,468,80000,363);
Insert into C##USERSQL.BILL_DETAIL_SEAT (BILL_DETAIL_ID,BILL_ID,SEAT_STATUS_ID,PRICE,TICKET_ID) values (54,46,434,100000,361);
REM INSERTING into C##USERSQL.CUSTOMER
SET DEFINE OFF;
Insert into C##USERSQL.CUSTOMER (IDCUS,NAME,MEMBER,POINT) values (1,'A',1,7300);
Insert into C##USERSQL.CUSTOMER (IDCUS,NAME,MEMBER,POINT) values (2,'B',1,100);
Insert into C##USERSQL.CUSTOMER (IDCUS,NAME,MEMBER,POINT) values (7,'Le Tu Tuan',0,0);
Insert into C##USERSQL.CUSTOMER (IDCUS,NAME,MEMBER,POINT) values (5,'chu nam thang',0,0);
Insert into C##USERSQL.CUSTOMER (IDCUS,NAME,MEMBER,POINT) values (6,'Nguyen Huu Tai',0,0);
Insert into C##USERSQL.CUSTOMER (IDCUS,NAME,MEMBER,POINT) values (3,'Nguyen minh Phu',1,100);
REM INSERTING into C##USERSQL.FOOD
SET DEFINE OFF;
Insert into C##USERSQL.FOOD (FOOD_ID,FOOD_NAME,PRICE) values (1,'CoCa',10000);
Insert into C##USERSQL.FOOD (FOOD_ID,FOOD_NAME,PRICE) values (2,'Popcorn',20000);
REM INSERTING into C##USERSQL.MOVIE
SET DEFINE OFF;
Insert into C##USERSQL.MOVIE (ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,MOVIE_AGE) values (3,'Trolls','Animation',90,'P');
Insert into C##USERSQL.MOVIE (ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,MOVIE_AGE) values (10,'INVISIBLE EVIDENCE','Drama,Thriller',100,'18+');
Insert into C##USERSQL.MOVIE (ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,MOVIE_AGE) values (13,'INTRUDER','Thriller',102,'18+');
Insert into C##USERSQL.MOVIE (ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,MOVIE_AGE) values (1,'Star War','Vien Tuong',90,'20');
Insert into C##USERSQL.MOVIE (ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,MOVIE_AGE) values (2,'Fast and Furious','Action',90,'18+');
Insert into C##USERSQL.MOVIE (ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,MOVIE_AGE) values (12,'WITHOUT A BODY','Horror',90,'18');
Insert into C##USERSQL.MOVIE (ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,MOVIE_AGE) values (6,'Thor','Action',120,'P');
Insert into C##USERSQL.MOVIE (ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,MOVIE_AGE) values (15,'Nhiem Vu Bat Kha Thi','Action',90,'18+');
Insert into C##USERSQL.MOVIE (ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,MOVIE_AGE) values (9,'Black Widow','Action,Fantasy',90,'16+');
Insert into C##USERSQL.MOVIE (ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,MOVIE_AGE) values (5,'Movie B','Animation',90,'P');
Insert into C##USERSQL.MOVIE (ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,MOVIE_AGE) values (7,'100% Wolf','Animation',120,'P');
Insert into C##USERSQL.MOVIE (ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,MOVIE_AGE) values (8,'James Bond','Action',90,'18+');
Insert into C##USERSQL.MOVIE (ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,MOVIE_AGE) values (16,'SURVIVE THE NIGHT','Action,Thriller',90,'18+');
Insert into C##USERSQL.MOVIE (ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,MOVIE_AGE) values (11,'SCOOB','Animation,Comedy',93,'P');
Insert into C##USERSQL.MOVIE (ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,MOVIE_AGE) values (14,'THE VOICES','Horror,Thriller',96,'16+');
REM INSERTING into C##USERSQL.ROOM
SET DEFINE OFF;
Insert into C##USERSQL.ROOM (IDROOM,SEATS_NO) values (1,30);
Insert into C##USERSQL.ROOM (IDROOM,SEATS_NO) values (2,20);
REM INSERTING into C##USERSQL.SEAT
SET DEFINE OFF;
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (1,'A',1,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (2,'A',2,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (3,'A',3,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (4,'A',4,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (5,'A',5,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (6,'B',1,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (7,'B',2,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (8,'B',3,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (9,'B',4,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (10,'B',5,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (11,'C',1,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (12,'C',2,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (13,'C',3,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (14,'C',4,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (15,'C',5,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (16,'D',1,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (17,'D',2,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (18,'D',3,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (19,'D',4,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (20,'D',5,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (21,'E',1,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (22,'E',2,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (23,'E',3,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (24,'E',4,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (25,'E',5,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (26,'F',1,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (27,'F',2,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (28,'F',3,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (29,'F',4,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (30,'F',5,1);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (31,'A',1,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (32,'A',2,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (33,'A',3,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (34,'A',4,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (35,'A',5,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (36,'B',1,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (37,'B',2,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (38,'B',3,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (39,'B',4,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (40,'B',5,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (41,'C',1,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (42,'C',2,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (43,'C',3,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (44,'C',4,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (45,'C',5,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (46,'D',1,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (47,'D',2,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (48,'D',3,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (49,'D',4,2);
Insert into C##USERSQL.SEAT (IDSEAT,ROW_SEAT,NUMBER_SEAT,IDROOM) values (50,'D',5,2);
REM INSERTING into C##USERSQL.SEAT_STATUS
SET DEFINE OFF;
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (224,10,31,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (225,10,32,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (226,10,33,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (227,10,34,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (228,10,35,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (229,10,36,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (230,10,37,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (231,10,38,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (232,10,39,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (233,10,40,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (234,10,41,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (235,10,42,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (236,10,43,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (237,10,44,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (238,10,45,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (239,10,46,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (240,10,47,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (241,10,48,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (242,10,49,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (243,10,50,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (833,3,31,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (834,3,32,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (835,3,33,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (836,3,34,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (837,3,35,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (838,3,36,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (839,3,37,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (840,3,38,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (841,3,39,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (842,3,40,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (843,3,41,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (844,3,42,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (845,3,43,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (846,3,44,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (847,3,45,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (848,3,46,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (849,3,47,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (850,3,48,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (851,3,49,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (852,3,50,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (311,11,31,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (312,11,32,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (313,11,33,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (314,11,34,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (315,11,35,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (316,11,36,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (317,11,37,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (318,11,38,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (319,11,39,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (320,11,40,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (321,11,41,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (322,11,42,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (323,11,43,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (324,11,44,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (325,11,45,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (326,11,46,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (327,11,47,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (328,11,48,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (329,11,49,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (330,11,50,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (813,2,31,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (814,2,32,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (815,2,33,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (816,2,34,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (817,2,35,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (818,2,36,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (819,2,37,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (820,2,38,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (821,2,39,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (822,2,40,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (823,2,41,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (824,2,42,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (825,2,43,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (826,2,44,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (827,2,45,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (828,2,46,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (829,2,47,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (830,2,48,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (831,2,49,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (832,2,50,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (246,9,1,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (247,9,2,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (248,9,3,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (249,9,4,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (250,9,5,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (251,9,6,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (252,9,7,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (253,9,8,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (254,9,9,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (255,9,10,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (256,9,11,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (257,9,12,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (258,9,13,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (259,9,14,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (260,9,15,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (261,9,16,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (262,9,17,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (263,9,18,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (264,9,19,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (265,9,20,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (266,9,21,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (267,9,22,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (268,9,23,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (269,9,24,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (270,9,25,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (271,9,26,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (272,9,27,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (273,9,28,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (274,9,29,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (275,9,30,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (112,5,31,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (113,5,32,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (114,5,33,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (115,5,34,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (116,5,35,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (117,5,36,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (118,5,37,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (119,5,38,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (120,5,39,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (121,5,40,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (122,5,41,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (123,5,42,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (124,5,43,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (125,5,44,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (126,5,45,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (127,5,46,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (128,5,47,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (129,5,48,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (130,5,49,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (131,5,50,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (149,6,31,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (150,6,32,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (151,6,33,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (152,6,34,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (153,6,35,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (154,6,36,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (155,6,37,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (156,6,38,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (157,6,39,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (158,6,40,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (159,6,41,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (160,6,42,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (161,6,43,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (162,6,44,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (163,6,45,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (164,6,46,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (165,6,47,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (166,6,48,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (167,6,49,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (168,6,50,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (171,7,1,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (172,7,2,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (173,7,3,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (174,7,4,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (175,7,5,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (176,7,6,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (177,7,7,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (178,7,8,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (179,7,9,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (180,7,10,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (181,7,11,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (182,7,12,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (183,7,13,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (184,7,14,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (185,7,15,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (186,7,16,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (187,7,17,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (188,7,18,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (189,7,19,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (190,7,20,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (191,7,21,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (192,7,22,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (193,7,23,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (194,7,24,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (195,7,25,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (196,7,26,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (197,7,27,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (198,7,28,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (199,7,29,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (200,7,30,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (853,18,1,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (854,18,2,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (855,18,3,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (856,18,4,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (857,18,5,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (858,18,6,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (859,18,7,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (860,18,8,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (861,18,9,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (862,18,10,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (863,18,11,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (864,18,12,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (865,18,13,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (866,18,14,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (867,18,15,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (868,18,16,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (869,18,17,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (870,18,18,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (871,18,19,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (872,18,20,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (463,13,31,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (464,13,32,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (465,13,33,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (466,13,34,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (467,13,35,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (468,13,36,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (469,13,37,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (470,13,38,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (471,13,39,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (472,13,40,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (473,13,41,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (474,13,42,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (475,13,43,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (476,13,44,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (477,13,45,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (478,13,46,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (479,13,47,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (480,13,48,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (481,13,49,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (482,13,50,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (873,18,21,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (874,18,22,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (875,18,23,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (876,18,24,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (877,18,25,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (878,18,26,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (879,18,27,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (880,18,28,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (881,18,29,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (882,18,30,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (433,12,1,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (434,12,2,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (435,12,3,'1');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (436,12,4,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (437,12,5,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (438,12,6,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (439,12,7,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (440,12,8,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (441,12,9,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (442,12,10,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (443,12,11,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (444,12,12,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (445,12,13,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (446,12,14,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (447,12,15,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (448,12,16,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (449,12,17,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (450,12,18,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (451,12,19,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (452,12,20,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (453,12,21,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (454,12,22,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (455,12,23,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (456,12,24,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (457,12,25,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (458,12,26,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (459,12,27,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (460,12,28,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (461,12,29,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (462,12,30,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (583,17,31,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (584,17,32,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (585,17,33,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (586,17,34,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (587,17,35,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (588,17,36,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (589,17,37,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (590,17,38,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (591,17,39,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (592,17,40,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (593,17,41,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (594,17,42,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (595,17,43,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (596,17,44,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (597,17,45,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (598,17,46,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (599,17,47,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (600,17,48,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (601,17,49,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (602,17,50,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (783,4,1,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (784,4,2,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (785,4,3,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (786,4,4,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (787,4,5,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (788,4,6,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (789,4,7,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (790,4,8,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (791,4,9,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (792,4,10,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (793,4,11,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (794,4,12,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (795,4,13,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (796,4,14,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (797,4,15,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (798,4,16,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (799,4,17,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (800,4,18,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (801,4,19,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (802,4,20,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (803,4,21,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (804,4,22,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (805,4,23,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (806,4,24,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (807,4,25,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (808,4,26,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (809,4,27,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (810,4,28,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (811,4,29,'0');
Insert into C##USERSQL.SEAT_STATUS (IDSEAT_STATUS,ID_SHOWTIME,ID_SEAT,STATUS) values (812,4,30,'0');
REM INSERTING into C##USERSQL.SHOWTIME
SET DEFINE OFF;
Insert into C##USERSQL.SHOWTIME (ID,MOVIE_ID,ROOM_ID,TIME_START,COST,TIME_END,DATE_ST) values (3,8,2,'09:15',100000,'10:30',to_date('10-JUL-20','DD-MON-RR'));
Insert into C##USERSQL.SHOWTIME (ID,MOVIE_ID,ROOM_ID,TIME_START,COST,TIME_END,DATE_ST) values (10,3,2,'19:00',90000,'21:00',to_date('02-JUL-20','DD-MON-RR'));
Insert into C##USERSQL.SHOWTIME (ID,MOVIE_ID,ROOM_ID,TIME_START,COST,TIME_END,DATE_ST) values (11,3,2,'07:00',100000,'08:30',to_date('09-JUL-20','DD-MON-RR'));
Insert into C##USERSQL.SHOWTIME (ID,MOVIE_ID,ROOM_ID,TIME_START,COST,TIME_END,DATE_ST) values (2,15,2,'07:00',100000,'09:00',to_date('10-JUL-20','DD-MON-RR'));
Insert into C##USERSQL.SHOWTIME (ID,MOVIE_ID,ROOM_ID,TIME_START,COST,TIME_END,DATE_ST) values (9,3,1,'07:00',180000,'09:00',to_date('05-JUL-20','DD-MON-RR'));
Insert into C##USERSQL.SHOWTIME (ID,MOVIE_ID,ROOM_ID,TIME_START,COST,TIME_END,DATE_ST) values (5,1,2,'07:00',70000,'09:00',to_date('01-JUL-20','DD-MON-RR'));
Insert into C##USERSQL.SHOWTIME (ID,MOVIE_ID,ROOM_ID,TIME_START,COST,TIME_END,DATE_ST) values (6,2,2,'12:00',120000,'13:30',to_date('03-JUL-20','DD-MON-RR'));
Insert into C##USERSQL.SHOWTIME (ID,MOVIE_ID,ROOM_ID,TIME_START,COST,TIME_END,DATE_ST) values (7,1,1,'15:00',100000,'16:30',to_date('03-JUL-20','DD-MON-RR'));
Insert into C##USERSQL.SHOWTIME (ID,MOVIE_ID,ROOM_ID,TIME_START,COST,TIME_END,DATE_ST) values (13,7,2,'10:00',80000,'11:30',to_date('09-JUL-20','DD-MON-RR'));
Insert into C##USERSQL.SHOWTIME (ID,MOVIE_ID,ROOM_ID,TIME_START,COST,TIME_END,DATE_ST) values (18,13,1,'20:00',100000,'22:00',to_date('10-JUL-20','DD-MON-RR'));
Insert into C##USERSQL.SHOWTIME (ID,MOVIE_ID,ROOM_ID,TIME_START,COST,TIME_END,DATE_ST) values (17,3,2,'14:00',100000,'15:00',to_date('02-JUL-20','DD-MON-RR'));
Insert into C##USERSQL.SHOWTIME (ID,MOVIE_ID,ROOM_ID,TIME_START,COST,TIME_END,DATE_ST) values (12,6,1,'07:00',100000,'08:45',to_date('09-JUL-20','DD-MON-RR'));
Insert into C##USERSQL.SHOWTIME (ID,MOVIE_ID,ROOM_ID,TIME_START,COST,TIME_END,DATE_ST) values (4,3,1,'08:00',100000,'10:00',to_date('10-JUL-20','DD-MON-RR'));
REM INSERTING into C##USERSQL.STAFF
SET DEFINE OFF;
Insert into C##USERSQL.STAFF (ID_STAFF,NAME_STAFF,DATE_BIRTH,USERNAME,PASSWORD,ROLE) values (5,'Phan Vo Hieu Nghia',to_date('04-JUL-00','DD-MON-RR'),'nghia','1','Staff');
Insert into C##USERSQL.STAFF (ID_STAFF,NAME_STAFF,DATE_BIRTH,USERNAME,PASSWORD,ROLE) values (1,'Nguyen Van A',to_date('03-JUL-20','DD-MON-RR'),'a','12345','Staff');
Insert into C##USERSQL.STAFF (ID_STAFF,NAME_STAFF,DATE_BIRTH,USERNAME,PASSWORD,ROLE) values (2,'Nguyen Van B',to_date('11-JUL-00','DD-MON-RR'),'b','12345','Staff');
Insert into C##USERSQL.STAFF (ID_STAFF,NAME_STAFF,DATE_BIRTH,USERNAME,PASSWORD,ROLE) values (4,'Chung Quang Nhut',to_date('09-JUL-00','DD-MON-RR'),'manager','1','Manager');
Insert into C##USERSQL.STAFF (ID_STAFF,NAME_STAFF,DATE_BIRTH,USERNAME,PASSWORD,ROLE) values (185121361,'Nguyen Huu Tai',to_date('27-APR-00','DD-MON-RR'),'boss','1','Admin');
REM INSERTING into C##USERSQL.TICKET
SET DEFINE OFF;
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (391,3,'Adult',100000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (392,3,'Child',80000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (244,10,'Adult',90000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (245,10,'Child',72000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (309,11,'Adult',100000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (310,11,'Child',80000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (389,2,'Adult',100000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (390,2,'Child',80000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (276,9,'Adult',180000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (277,9,'Child',144000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (169,6,'Adult',120000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (170,6,'Child',96000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (201,7,'Adult',100000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (202,7,'Child',80000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (401,18,'Adult',100000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (363,13,'Adult',80000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (364,13,'Child',64000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (402,18,'Child',80000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (5,5,'Adult',70000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (6,5,'Child',50000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (361,12,'Adult',100000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (362,12,'Child',80000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (373,17,'Adult',100000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (374,17,'Child',80000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (387,4,'Adult',100000);
Insert into C##USERSQL.TICKET (TICKET_ID,SHOWTIME_ID,TICKET_TYPE,PRICE) values (388,4,'Child',80000);
--------------------------------------------------------
--  DDL for Index BILL_DETAIL_FOOD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERSQL"."BILL_DETAIL_FOOD_PK" ON "C##USERSQL"."BILL_DETAIL_FOOD" ("BILL_DETAIL_FOOD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BILL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERSQL"."BILL_PK" ON "C##USERSQL"."BILL" ("BILL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BILL_DETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERSQL"."BILL_DETAIL_PK" ON "C##USERSQL"."BILL_DETAIL_SEAT" ("BILL_DETAIL_ID", "SEAT_STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERSQL"."CUSTOMER_PK" ON "C##USERSQL"."CUSTOMER" ("IDCUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FOOD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERSQL"."FOOD_PK" ON "C##USERSQL"."FOOD" ("FOOD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MOVIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERSQL"."MOVIE_PK" ON "C##USERSQL"."MOVIE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROOM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERSQL"."ROOM_PK" ON "C##USERSQL"."ROOM" ("IDROOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SEAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERSQL"."SEAT_PK" ON "C##USERSQL"."SEAT" ("IDSEAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SEAT_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERSQL"."SEAT_STATUS_PK" ON "C##USERSQL"."SEAT_STATUS" ("IDSEAT_STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SHOWTIME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERSQL"."SHOWTIME_PK" ON "C##USERSQL"."SHOWTIME" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STAFF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERSQL"."STAFF_PK" ON "C##USERSQL"."STAFF" ("ID_STAFF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TICKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERSQL"."TICKET_PK" ON "C##USERSQL"."TICKET" ("TICKET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TG_INSBILLDETAIL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##USERSQL"."TG_INSBILLDETAIL" 
  AFTER INSERT  ON BILL_DETAIL_SEAT
  FOR EACH ROW
DECLARE
  idseat_status  NUMBER;
BEGIN
  idseat_status := :new.seat_status_id;
  updatestatusseats(idseat_status);
END;
/
ALTER TRIGGER "C##USERSQL"."TG_INSBILLDETAIL" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_UPDATE_CUSTOMER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##USERSQL"."TRIGGER_UPDATE_CUSTOMER" 
  AFTER Update  ON Customer
  FOR EACH ROW
DECLARE
BEGIN
    if :new.point >= 100 then
    update customer set member = 1 where idcus = :new.idcus;
    end if;
END; 
/
ALTER TRIGGER "C##USERSQL"."TRIGGER_UPDATE_CUSTOMER" DISABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_TRIGGER_IDSEAT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##USERSQL"."AUTO_INCREMENT_TRIGGER_IDSEAT" 
   before insert on "C##USERSQL"."SEAT" 
   for each row 
begin  
   if inserting then 
      if :NEW."IDSEAT" is null then 
         select MOVIE_SEQUENCE.nextval into :NEW."IDSEAT" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "C##USERSQL"."AUTO_INCREMENT_TRIGGER_IDSEAT" DISABLE;
--------------------------------------------------------
--  DDL for Trigger ATUO_TANG_IDSEAT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##USERSQL"."ATUO_TANG_IDSEAT" 
   before insert on "C##USERSQL"."SEAT" 
   for each row 
begin  
   if inserting then 
      if :NEW."IDSEAT" is null then 
         select MOVIE_SEQUENCE.nextval into :NEW."IDSEAT" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "C##USERSQL"."ATUO_TANG_IDSEAT" DISABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_TRIGGER_IDSEAT_STATUS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##USERSQL"."AUTO_INCREMENT_TRIGGER_IDSEAT_STATUS" 
   before insert on "C##USERSQL"."SEAT_STATUS" 
   for each row 
begin  
   if inserting then 
      if :NEW."IDSEAT_STATUS" is null then 
         select AUTO_TANG_ID_SEAT_STATUS.nextval into :NEW."IDSEAT_STATUS" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "C##USERSQL"."AUTO_INCREMENT_TRIGGER_IDSEAT_STATUS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_DELSHOWTIME
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##USERSQL"."TG_DELSHOWTIME" 
BEFORE DELETE ON ShowTime
for EACH row
DECLARE
Begin
     DELETE FROM seat_status WHERE :old.ID = id_showtime;
End;
/
ALTER TRIGGER "C##USERSQL"."TG_DELSHOWTIME" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_INSSHOWTIME
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##USERSQL"."TG_INSSHOWTIME" 
  AFTER INSERT  ON Showtime
  FOR EACH ROW
DECLARE
    idst Number := :new.ID;
    idseat number;
    numberofseat number;
BEGIN
    numberofseat := proc_numberofseat_room(:new.Room_ID);
--    Insert into ticket(showtime_id,ticket_type,price) values(:new.id,'Adult',:new.cost);
--    Insert into ticket(showtime_id,ticket_type,price) values(:new.id,'Child',:new.cost*0.8);
    FOR i IN 1..numberofseat LOOP
    idseat := func_get_idseat(:new.Room_ID,i);
    proc_insert_Seat_status(:new.ID,idseat);
    end loop;
END;
/
ALTER TRIGGER "C##USERSQL"."TG_INSSHOWTIME" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_UPDATECOSTSHOWTIME
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##USERSQL"."TG_UPDATECOSTSHOWTIME" 
  AFTER Update  ON Showtime
  FOR EACH ROW
DECLARE
BEGIN
    Update ticket set price = :new.cost where showtime_id = :new.id and ticket_type = 'Adult';
    Update ticket set price = :new.cost*0.8 where showtime_id = :new.id and ticket_type = 'Child';
END;
/
ALTER TRIGGER "C##USERSQL"."TG_UPDATECOSTSHOWTIME" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_ID_TICKET
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##USERSQL"."AUTO_ID_TICKET" 
   before insert on "C##USERSQL"."TICKET" 
   for each row 
begin  
   if inserting then 
      if :NEW."TICKET_ID" is null then 
         select MOVIE_SEQUENCE.nextval into :NEW."TICKET_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "C##USERSQL"."AUTO_ID_TICKET" ENABLE;
--------------------------------------------------------
--  Constraints for Table BILL_DETAIL_FOOD
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."BILL_DETAIL_FOOD" MODIFY ("BILL_DETAIL_FOOD" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."BILL_DETAIL_FOOD" MODIFY ("BILL_ID" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."BILL_DETAIL_FOOD" MODIFY ("FOOD_ID" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."BILL_DETAIL_FOOD" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."BILL_DETAIL_FOOD" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."BILL_DETAIL_FOOD" ADD CONSTRAINT "BILL_DETAIL_FOOD_PK" PRIMARY KEY ("BILL_DETAIL_FOOD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BILL
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."BILL" MODIFY ("BILL_ID" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."BILL" MODIFY ("STAFF_ID" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."BILL" MODIFY ("DATE_BILL" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."BILL" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."BILL" ADD CONSTRAINT "BILL_PK" PRIMARY KEY ("BILL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##USERSQL"."BILL" MODIFY ("SHOWTIME_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BILL_DETAIL_SEAT
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."BILL_DETAIL_SEAT" MODIFY ("BILL_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."BILL_DETAIL_SEAT" MODIFY ("BILL_ID" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."BILL_DETAIL_SEAT" ADD CONSTRAINT "BILL_DETAIL_PK" PRIMARY KEY ("BILL_DETAIL_ID", "SEAT_STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##USERSQL"."BILL_DETAIL_SEAT" MODIFY ("SEAT_STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."BILL_DETAIL_SEAT" MODIFY ("PRICE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."CUSTOMER" MODIFY ("IDCUS" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."CUSTOMER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."CUSTOMER" MODIFY ("MEMBER" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("IDCUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOOD
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."FOOD" MODIFY ("FOOD_ID" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."FOOD" MODIFY ("FOOD_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."FOOD" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."FOOD" ADD CONSTRAINT "FOOD_PK" PRIMARY KEY ("FOOD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MOVIE
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."MOVIE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."MOVIE" MODIFY ("MOVIE_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."MOVIE" MODIFY ("MOVIE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."MOVIE" MODIFY ("MOVIE_DURATION" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."MOVIE" MODIFY ("MOVIE_AGE" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."MOVIE" ADD CONSTRAINT "MOVIE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROOM
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."ROOM" MODIFY ("IDROOM" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."ROOM" MODIFY ("SEATS_NO" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."ROOM" ADD CONSTRAINT "ROOM_PK" PRIMARY KEY ("IDROOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEAT
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."SEAT" MODIFY ("IDSEAT" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."SEAT" MODIFY ("ROW_SEAT" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."SEAT" MODIFY ("NUMBER_SEAT" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."SEAT" MODIFY ("IDROOM" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."SEAT" ADD CONSTRAINT "SEAT_PK" PRIMARY KEY ("IDSEAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEAT_STATUS
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."SEAT_STATUS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."SEAT_STATUS" MODIFY ("IDSEAT_STATUS" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."SEAT_STATUS" MODIFY ("ID_SHOWTIME" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."SEAT_STATUS" MODIFY ("ID_SEAT" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."SEAT_STATUS" ADD CONSTRAINT "SEAT_STATUS_PK" PRIMARY KEY ("IDSEAT_STATUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SHOWTIME
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."SHOWTIME" MODIFY ("MOVIE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."SHOWTIME" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."SHOWTIME" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."SHOWTIME" ADD CONSTRAINT "SHOWTIME_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."STAFF" MODIFY ("ID_STAFF" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."STAFF" MODIFY ("NAME_STAFF" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."STAFF" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."STAFF" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."STAFF" ADD CONSTRAINT "STAFF_PK" PRIMARY KEY ("ID_STAFF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."TICKET" MODIFY ("TICKET_ID" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."TICKET" MODIFY ("SHOWTIME_ID" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."TICKET" MODIFY ("TICKET_TYPE" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."TICKET" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##USERSQL"."TICKET" ADD CONSTRAINT "TICKET_PK" PRIMARY KEY ("TICKET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BILL_DETAIL_FOOD
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."BILL_DETAIL_FOOD" ADD CONSTRAINT "BILL_DETAIL_FOOD_FK1" FOREIGN KEY ("BILL_ID")
	  REFERENCES "C##USERSQL"."BILL" ("BILL_ID") ENABLE;
  ALTER TABLE "C##USERSQL"."BILL_DETAIL_FOOD" ADD CONSTRAINT "BILL_DETAIL_FOOD_FK2" FOREIGN KEY ("FOOD_ID")
	  REFERENCES "C##USERSQL"."FOOD" ("FOOD_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BILL
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."BILL" ADD CONSTRAINT "BILL_FK3" FOREIGN KEY ("CUS_ID")
	  REFERENCES "C##USERSQL"."CUSTOMER" ("IDCUS") ENABLE;
  ALTER TABLE "C##USERSQL"."BILL" ADD CONSTRAINT "BILL_FK1" FOREIGN KEY ("STAFF_ID")
	  REFERENCES "C##USERSQL"."STAFF" ("ID_STAFF") ENABLE;
  ALTER TABLE "C##USERSQL"."BILL" ADD CONSTRAINT "BILL_FK2" FOREIGN KEY ("SHOWTIME_ID")
	  REFERENCES "C##USERSQL"."SHOWTIME" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BILL_DETAIL_SEAT
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."BILL_DETAIL_SEAT" ADD CONSTRAINT "BILL_DETAIL_FK1" FOREIGN KEY ("BILL_ID")
	  REFERENCES "C##USERSQL"."BILL" ("BILL_ID") ENABLE;
  ALTER TABLE "C##USERSQL"."BILL_DETAIL_SEAT" ADD CONSTRAINT "BILL_DETAIL_FK2" FOREIGN KEY ("SEAT_STATUS_ID")
	  REFERENCES "C##USERSQL"."SEAT_STATUS" ("IDSEAT_STATUS") ENABLE;
  ALTER TABLE "C##USERSQL"."BILL_DETAIL_SEAT" ADD CONSTRAINT "BILL_DETAIL_SEAT_FK1" FOREIGN KEY ("TICKET_ID")
	  REFERENCES "C##USERSQL"."TICKET" ("TICKET_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEAT
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."SEAT" ADD CONSTRAINT "FK_SEAT_ROOM" FOREIGN KEY ("IDROOM")
	  REFERENCES "C##USERSQL"."ROOM" ("IDROOM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEAT_STATUS
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."SEAT_STATUS" ADD CONSTRAINT "FK_SEAT_STATUS_SHOWTIME" FOREIGN KEY ("ID_SHOWTIME")
	  REFERENCES "C##USERSQL"."SHOWTIME" ("ID") ENABLE;
  ALTER TABLE "C##USERSQL"."SEAT_STATUS" ADD CONSTRAINT "FK_SEAT_STATUS_SEAT" FOREIGN KEY ("ID_SEAT")
	  REFERENCES "C##USERSQL"."SEAT" ("IDSEAT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SHOWTIME
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."SHOWTIME" ADD CONSTRAINT "FK_SHOWTIME_MOVIE" FOREIGN KEY ("MOVIE_ID")
	  REFERENCES "C##USERSQL"."MOVIE" ("ID") ENABLE;
  ALTER TABLE "C##USERSQL"."SHOWTIME" ADD CONSTRAINT "FK_SHOWTIME_ROOM" FOREIGN KEY ("ROOM_ID")
	  REFERENCES "C##USERSQL"."ROOM" ("IDROOM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "C##USERSQL"."TICKET" ADD CONSTRAINT "TICKET_FK1" FOREIGN KEY ("SHOWTIME_ID")
	  REFERENCES "C##USERSQL"."SHOWTIME" ("ID") ENABLE;
